#!/usr/bin/env perl
use strict;
use warnings;

use File::Basename 'dirname';
use File::Spec;

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

eval 'use Mojolicious::Commands';
die <<EOF if $@;
  It looks like you don't have the Mojolicious Framework installed.
  Please visit http://mojolicio.us for detailed installation instructions.

EOF
$ENV{MOJO_APP} ||= 'MyApp';

Mojolicious::Commands->start;
